# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pr: none

variables:
 vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildSite
        displayName: 'Build Site'
        pool:
          vmImage: $(vmImageName)
        
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
          displayName: 'Install NodeJS'

        - script: |
            npm install
            npm install @babel/helper-compilation-targets --save-dev
            npm run build --if-present
          displayName: 'npm install and build'

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/dist/'
            Contents: '$(System.DefaultWorkingDirectory)/dist/**/*'
            TargetFolder: '$(Build.ArtifactStagingDirectory)/output-site'
          displayName: 'Copy site files to artifact directory'
        
        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/output-site'
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-Site.zip
            replaceExistingArchive: true

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-site.zip'
            artifact: '$(Build.BuildId)-Site.zip'
        
        

